# Generated by Django 5.2.1 on 2025-05-24 07:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_task_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('title', 'due_date', 'user')},
        ),
    ]
